~assist_compose_page_func = {

	/*
	WHAT WE WANT

	- All functionality on the assist compose page - play button, rate, slider, etc
	- *everything* can be saved for a later date
	-
	*/

	~firstview = View(w, Rect(0, 0, w.bounds.width, w.bounds.height));
	/*view.clearOnRefresh = false;*/
	~firstview.background = ~backgroundcolor;
	~firstviewboundsWIDTH = ~firstview.bounds.width;
	~firstviewboundsHEIGHT = ~firstview.bounds.height;



};